In [1]:
import pandas as pd
df = pd.read_json("test.jsonl", lines=True)

In [2]:
df

         text  label
0   i love AI      1
1  this sucks      0
2  AI is cool      1
3        None      0

In [3]:
df = df.dropna()

In [4]:
df

         text  label
0   i love AI      1
1  this sucks      0
2  AI is cool      1

In [5]:
df["text"] = df["text"].str.lower()

/tmp/ipykernel_366109/2070785541.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].str.lower()

In [6]:
df

         text  label
0   i love ai      1
1  this sucks      0
2  ai is cool      1

In [7]:
df["length"] = df["text"].apply(len)

/tmp/ipykernel_366109/899142544.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["length"] = df["text"].apply(len)

In [8]:
df

         text  label  length
0   i love ai      1       9
1  this sucks      0      10
2  ai is cool      1      10

In [9]:
df_pos = df[df["label"] == 1]

In [10]:
df_pos

         text  label  length
0   i love ai      1       9
2  ai is cool      1      10

In [11]:
texts = df["text"].tolist()
labels = df["label"].tolist()

In [12]:
texts, labels

(['i love ai', 'this sucks', 'ai is cool'], [1, 0, 1])

In [3]:
import pandas as pd
df = pd.read_json("test.jsonl", lines=True)

In [4]:
df

         text  label
0   i love AI      1
1  this sucks      0
2  AI is cool      1
3        None      0

In [5]:
df = df.dropna()

In [6]:
df

         text  label
0   i love AI      1
1  this sucks      0
2  AI is cool      1

In [7]:
df['text'] = df['text'].str.upper()

/tmp/ipykernel_503550/2551732280.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].str.upper()

In [8]:
df

         text  label
0   I LOVE AI      1
1  THIS SUCKS      0
2  AI IS COOL      1

In [26]:
df["words"] = df['text'].apply(lambda x: len(x.split()))

/tmp/ipykernel_503550/957883173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["words"] = df['text'].apply(lambda x: len(x.split()))

In [27]:
df

         text  label  words
0   I LOVE AI      1      3
1  THIS SUCKS      0      2
2  AI IS COOL      1      3

In [24]:
df_neg = df[df['label'] == 0]

In [25]:
df_neg

         text  label  words
1  THIS SUCKS      0      3

In [ ]:
import pandas as pd
df = pd.read_json("test.jsonl", lines=True)
df = df.dropna()
df['text'] = df['text'].str.upper()
df["words"] = df['text'].apply(lambda x: x.split())
df_neg = df[df['label'] == 0]