In [10]:
import pandas as pd
df = pd.read_json('messy_posts.jsonl', lines=True)

In [11]:
df = df.dropna()

In [12]:
df

                              text     label
0                     I LOVE AI!!!  positive
1                this sucks so bad  negative
3      machine learning is cool     positive
4              BRO WHAT IS THIS 😭😭  negative
5                     i love ai!!!  positive
6                                   negative
7                Python is AWESOME  positive
9                           123456  negative
10                              ok   neutral
11                    I LOVE AI!!!  positive
12                                  negative
13              deep learning >>>>  positive
14    why is this model so dumb???  negative

In [13]:
df = df.drop([6, 12])

In [14]:
df

                              text     label
0                     I LOVE AI!!!  positive
1                this sucks so bad  negative
3      machine learning is cool     positive
4              BRO WHAT IS THIS 😭😭  negative
5                     i love ai!!!  positive
7                Python is AWESOME  positive
9                           123456  negative
10                              ok   neutral
11                    I LOVE AI!!!  positive
13              deep learning >>>>  positive
14    why is this model so dumb???  negative

In [15]:
df['text'] = df['text'].str.lower()

In [16]:
df

                              text     label
0                     i love ai!!!  positive
1                this sucks so bad  negative
3      machine learning is cool     positive
4              bro what is this 😭😭  negative
5                     i love ai!!!  positive
7                python is awesome  positive
9                           123456  negative
10                              ok   neutral
11                    i love ai!!!  positive
13              deep learning >>>>  positive
14    why is this model so dumb???  negative

In [17]:
df = df.drop_duplicates()

In [18]:
df

                              text     label
0                     i love ai!!!  positive
1                this sucks so bad  negative
3      machine learning is cool     positive
4              bro what is this 😭😭  negative
7                python is awesome  positive
9                           123456  negative
10                              ok   neutral
13              deep learning >>>>  positive
14    why is this model so dumb???  negative

In [19]:
df["text"] = df["text"].str.strip()

/tmp/ipykernel_4186001/2086694713.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"] = df["text"].str.strip()

In [42]:
df

                            text  label  char_count  word_count
0                   i love ai!!!      1          12           3
1              this sucks so bad      0          17           4
3       machine learning is cool      1          24           4
4            bro what is this 😭😭      0          19           5
7              python is awesome      1          17           3
9                         123456      0           6           1
10                            ok      2           2           1
13            deep learning >>>>      1          18           3
14  why is this model so dumb???      0          28           6

In [41]:
df = df.drop(columns=['features', 'char'])

In [31]:
def feature(x):
    if x == "positive":
        return 1
    elif x == "negative":
        return 0
    else: 
        return 2
df['label'] = df['label'].apply(feature)

/tmp/ipykernel_4186001/1532793792.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = df['label'].apply(feature)

In [35]:
df['char_count'] = df['text'].apply(len)
df['word_count'] = df['text'].apply(lambda x: len(x.split()))

/tmp/ipykernel_4186001/2400772603.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['char_count'] = df['text'].apply(len)
/tmp/ipykernel_4186001/2400772603.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['word_count'] = df['text'].apply(lambda x: len(x.split()))

In [ ]:
import pandas as pd
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
df = pd.read_json('messy_posts.jsonl', lines=True)
df = df.dropna()
df = df[df['text'].str.strip() != ""]
df['text'] = df['text'].str.lower()
df["text"] = df["text"].str.strip()
df = df.drop_duplicates(subset=['text'])
mapping = {
    "positive":1,
    "negative":0,
    "neutral":2
}
df['label'] = df['label'].map(mapping)
df['char_count'] = df['text'].apply(len)
df['word_count'] = df['text'].apply(lambda x: len(x.split()))

class TextDataset(Dataset):
    def __init__(self, df):
        self.texts = df["text"].tolist()
        self.labels = df["label"].tolist()

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        return text, label
dataset = TextDataset(df)
loader = DataLoader(dataset, batch_size = 2, shuffle=True)