In [27]:
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
data = []
for i in range(1, 11):

    driver.get(f"https://quotes.toscrape.com/page/{i}/")

    quotes = driver.find_elements(By.CLASS_NAME, "quote")
    for quote in quotes:
        text = quote.find_element(By.CLASS_NAME, "text").text
        author = quote.find_element(By.CLASS_NAME, "author").text
        data.append({
            "quote":text,
            "author":author
        })
driver.quit()

In [21]:
import pandas as pd
df = pd.DataFrame(data)

In [22]:
df

                                                quote              author
0   “The world as we have created it is a process ...     Albert Einstein
1   “It is our choices, Harry, that show what we t...        J.K. Rowling
2   “There are only two ways to live your life. On...     Albert Einstein
3   “The person, be it gentleman or lady, who has ...         Jane Austen
4   “Imperfection is beauty, madness is genius and...      Marilyn Monroe
..                                                ...                 ...
95  “You never really understand a person until yo...          Harper Lee
96  “You have to write the book that wants to be w...   Madeleine L'Engle
97  “Never tell the truth to people who are not wo...          Mark Twain
98        “A person's a person, no matter how small.”           Dr. Seuss
99  “... a mind needs books as a sword needs a whe...  George R.R. Martin

[100 rows x 2 columns]

In [23]:
df = df.drop_duplicates()
df = df.dropna()

In [24]:
df["quote"] = df["quote"].str.strip()

In [25]:
df

                                                quote              author
0   “The world as we have created it is a process ...     Albert Einstein
1   “It is our choices, Harry, that show what we t...        J.K. Rowling
2   “There are only two ways to live your life. On...     Albert Einstein
3   “The person, be it gentleman or lady, who has ...         Jane Austen
4   “Imperfection is beauty, madness is genius and...      Marilyn Monroe
..                                                ...                 ...
95  “You never really understand a person until yo...          Harper Lee
96  “You have to write the book that wants to be w...   Madeleine L'Engle
97  “Never tell the truth to people who are not wo...          Mark Twain
98        “A person's a person, no matter how small.”           Dr. Seuss
99  “... a mind needs books as a sword needs a whe...  George R.R. Martin

[100 rows x 2 columns]

In [26]:
driver.quit()